import type { Destination } from "./types"
export const destinations: Destination[] = [
  {
    id: "1",
    name: "Andaman & Nicobar Islands",
    country: "India",
    image: "./images/states/AD.jpg",
    description:
      "A tropical paradise with pristine beaches, crystal-clear waters, and vibrant marine life. Perfect for scuba diving, snorkeling, and nature exploration.",
    rating: 4.8,
    reviewCount: 1520,
    weather: "Tropical",
    bestTimeToVisit: "Oct-May",
    region: "india",
    tripTypes: ["adventure", "romantic", "family"],
    budget: "medium",
    climate: "tropical",
    lat: 11.7401,
    lng: 92.6586,
  },
  {
    id: "2",
    name: "Arunachal Pradesh",
    country: "India",
    image: "./images/states/AR.jpeg",
    description:
      "A mystical land of mountains, monasteries, and rich tribal culture. Ideal for trekking, nature exploration, and spiritual retreats.",
    rating: 4.7,
    reviewCount: 1340,
    weather: "Cold and Pleasant",
    bestTimeToVisit: "Oct-Apr",
    region: "india",
    tripTypes: ["adventure", "nature", "cultural"],
    budget: "medium",
    climate: "temperate",
    lat: 27.1004,
    lng: 93.6167
  },  
  {
    id: "3",
    name: "Goa",
    country: "India",
    image: "./images/states/Goa.jpg",
    description:
      "Famous for its golden beaches, vibrant nightlife, and Portuguese heritage. Enjoy water sports, beach parties, and delicious seafood.",
    rating: 4.7,
    reviewCount: 3890,
    weather: "Tropical",
    bestTimeToVisit: "Nov-Feb",
    region: "india",
    tripTypes: ["beach", "party", "romantic"],
    budget: "medium",
    climate: "tropical",
    lat: 15.2993,
    lng: 74.124,
  },
  {
    id: "4",
    name: "Himachal Pradesh",
    country: "India",
    image: "./images/states/HimachalPradesh.jpg",
    description:
      "Nestled in the Himalayas, known for its picturesque landscapes, adventure sports, and hill stations like Manali and Shimla.",
    rating: 4.8,
    reviewCount: 2760,
    weather: "Cold",
    bestTimeToVisit: "Mar-Jun, Sep-Dec",
    region: "india",
    tripTypes: ["adventure", "nature", "family"],
    budget: "medium",
    climate: "cold",
    lat: 31.1048,
    lng: 77.1734,
  },
  {
    id: "5",
    name: "Jammu & Kashmir",
    country: "India",
    image: "./images/states/Jammu&Kashmir.jpeg",
    description:
      "The 'Paradise on Earth' with breathtaking valleys, snow-capped mountains, and houseboats in Dal Lake.",
    rating: 4.9,
    reviewCount: 3650,
    weather: "Cold",
    bestTimeToVisit: "Apr-Oct",
    region: "india",
    tripTypes: ["romantic", "nature", "adventure"],
    budget: "luxury",
    climate: "cold",
    lat: 33.7782,
    lng: 76.5762,
  },
  {
    id: "6",
    name: "Kerala",
    country: "India",
    image: "./images/states/Kerala.webp",
    description:
      "God's Own Country, famous for backwaters, lush greenery, Ayurveda, and pristine beaches.",
    rating: 4.9,
    reviewCount: 4890,
    weather: "Tropical",
    bestTimeToVisit: "Sep-Mar",
    region: "india",
    tripTypes: ["nature", "relaxation", "family"],
    budget: "medium",
    climate: "tropical",
    lat: 10.8505,
    lng: 76.2711,
  },
  {
    id: "7",
    name: "Meghalaya",
    country: "India",
    image: "./images/states/Meghalaya.jpg",
    description:
      "The Abode of Clouds, known for living root bridges, lush landscapes, and the cleanest village in Asia.",
    rating: 4.7,
    reviewCount: 1890,
    weather: "Moderate",
    bestTimeToVisit: "Oct-Apr",
    region: "india",
    tripTypes: ["nature", "adventure", "family"],
    budget: "medium",
    climate: "moderate",
    lat: 25.467,
    lng: 91.3662,
  },
  {
    id: "8",
    name: "Punjab",
    country: "India",
    image: "./images/states/PUNJAB.avif",
    description:
      "The land of five rivers, rich in history, culture, and spirituality. Visit the Golden Temple and Wagah Border ceremony.",
    rating: 4.6,
    reviewCount: 2430,
    weather: "Seasonal",
    bestTimeToVisit: "Oct-Mar",
    region: "india",
    tripTypes: ["cultural", "spiritual", "family"],
    budget: "medium",
    climate: "moderate",
    lat: 31.1471,
    lng: 75.3412,
  },
  {
    id: "9",
    name: "Rajasthan",
    country: "India",
    image: "./images/states/Rajasthan.jpg",
    description:
      "The land of kings, known for its majestic forts, palaces, desert safaris, and vibrant culture.",
    rating: 4.8,
    reviewCount: 4120,
    weather: "Hot",
    bestTimeToVisit: "Oct-Mar",
    region: "india",
    tripTypes: ["historical", "luxury", "family"],
    budget: "medium",
    climate: "hot",
    lat: 27.0238,
    lng: 74.2179,
  },
  {
    id: "10",
    name: "Sikkim",
    country: "India",
    image: "./images/states/Sikkim.jpg",
    description:
      "A scenic paradise nestled in the Himalayas, known for its breathtaking landscapes, monasteries, and rich biodiversity. Perfect for trekking, nature lovers, and cultural exploration.",
    rating: 4.8,
    reviewCount: 1450,
    weather: "Cold and Pleasant",
    bestTimeToVisit: "Mar-Jun, Sep-Dec",
    region: "india",
    tripTypes: ["adventure", "nature", "cultural"],
    budget: "medium",
    climate: "mountainous",
    lat: 27.533,
    lng: 88.5122
  },  
  {
    id: "11",
    name: "Tamil Nadu",
    country: "India",
    image: "./images/states/Tamil Nadu.webp",
    description:
      "A state rich in history, temples, beaches, and cultural heritage. Home to Mahabalipuram, Rameshwaram, and hill stations like Ooty.",
    rating: 4.7,
    reviewCount: 3560,
    weather: "Tropical",
    bestTimeToVisit: "Nov-Mar",
    region: "india",
    tripTypes: ["spiritual", "historical", "family"],
    budget: "medium",
    climate: "tropical",
    lat: 11.1271,
    lng: 78.6569,
  },
  {
    id: "12",
    name: "Uttarakhand",
    country: "India",
    image: "./images/states/Uttarakhand.jpg",
    description:
      "The Devbhumi (Land of Gods), known for Char Dham Yatra, trekking, and scenic hill stations like Nainital and Mussoorie.",
    rating: 4.8,
    reviewCount: 2780,
    weather: "Seasonal",
    bestTimeToVisit: "Apr-Jun, Sep-Nov",
    region: "india",
    tripTypes: ["spiritual", "adventure", "nature"],
    budget: "medium",
    climate: "moderate",
    lat: 30.0668,
    lng: 79.0193,
  },
];
